brew "bat"
brew "btop"
# docker formula not cask
brew "docker"
brew "cask"
brew "colima"
brew "eza"
brew "ffmpeg"
brew "fnm"
brew "fd"
brew "fuzzy-find"
brew "jump"
brew "ghostscript"
brew "gifsicle"
brew "glow"
brew "httpie"
brew "libavif"
brew "mas"
brew "fastfetch"
brew "go"
brew "neovim"
brew "ncdu"
brew "ripgrep"
brew "ruby"
brew "rustup-init"
brew "tree"
brew "typst"
brew "wget"
brew "xclip"
brew "zsh-vi-mode"

# General
cask "appcleaner"
cask "caffeine"
cask "chatgpt"
cask "datagrip"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "ghostty"
cask "keycastr"
cask "logi-options-plus"
cask "openinterminal"
cask "rectangle"
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
cask "zoom"
cask "slack"

# Personal
cask "1password"
cask "mactex-no-gui"
cask "telegram"
cask "temurin17"
cask "transmission"
cask "viber"
cask "vlc"
cask "whatsapp"

# VS Code Themes and Basics
vscode "GitHub.github-vscode-theme"
vscode "vscodevim.vim"
vscode "miguelsolorio.symbols"

# Mac App Store Apps - General
mas "Dropover - Easier Drag & Drop", id: 1355679052
