brew "bat"
brew "btop"
# docker formula not cask
brew "docker"
brew "cask"
brew "colima"
brew "eza"
brew "ffmpeg"
brew "fnm"
brew "fd"
brew "fzf"
brew "jump"
brew "ghostscript"
brew "gifsicle"
brew "glow"
brew "httpie"
brew "libavif"
brew "mas"
brew "fastfetch"
brew "go"
brew "neovim"
brew "ncdu"
brew "ripgrep"
brew "ruby"
brew "rustup-init"
brew "tree"
brew "typst"
brew "wget"
brew "xclip"
brew "zsh-vi-mode"

# General
cask "appcleaner"
cask "caffeine"
cask "chatgpt"
cask "claude"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "ghostty"
cask "keycastr"
cask "logi-options-plus"
cask "openinterminal"
cask "rectangle"
cask "spotify"
cask "the-unarchiver"
cask "zoom"
cask "slack"

# Personal
cask "1password"
cask "telegram"
cask "transmission"
cask "vlc"
cask "whatsapp"

# Work
cask "datagrip"

# Mac App Store Apps - General
mas "Dropover - Easier Drag & Drop", id: 1355679052
