format = "$model$thinking$directory$git_branch$activity$context$tokens$cache$cost"

[model]
symbol = "󰚩"

[thinking]
symbol = "󰔟"

[directory]
symbol = "󰉋"
format = "[$symbol $path ]($style)"

[git_branch]
symbol = ""
format = "[$symbol $branch ]($style)"

[activity]
symbol = "󰉁"
format = "[$text ]($style)"

[context]
format = "[$symbol $percentage ]($style)"
symbol = "󰊚"

[[context.display]]
threshold = 0
style = "bold green"
hidden = false

[[context.display]]
threshold = 60
style = "bold yellow"
hidden = false

[[context.display]]
threshold = 80
style = "bold red"
hidden = false

[tokens]
symbol = "󰆙"

[cache]
symbol = "󰆼"
disabled = false

[cost]
symbol = "󰄔"
format = "[$symbol \\$$cost( $subscription) ]($style)"
