[aws]
disabled = true

[gcloud]
disabled = true

[java]
disabled = true

[git_branch]
symbol = " "

[terraform]
format = "via [$symbol$version]($style)"
symbol = "󱁢 "

[golang]
symbol = "󰟓 "
format = 'via [$symbol($mod_version)]($style)'

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'bold yellow'
format = '\([$state( $progress_current/$progress_total)]($style)\)'
disabled = true

[git_status]
ahead = "↑${count} "
behind = "↓${count} "
diverged = "↕${ahead_count} ${behind_count}"
untracked = "?${count} "
modified = "!${count} "
conflicted = "≠${count} "
staged = "✓${count} "
stashed = "*${count} "
style = "bright-white"
format = """\
[$ahead_behind](bold green)\
[$stashed](bold green)\
[$behind_behind](bold red)\
[$diverged](bold yellow)\
[$conflicted](bold red)\
[$modified](bold blue)\
[$untracked](bold cyan)\
[$staged](bold green)\
"""
